[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
axum = "0.8.9"
tower-http = { version = "0.7", features = ["trace", "request-id"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
reqwest = "0.13.4"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde-aux = "4"
tokio = {version = "1.52.3", features = ["macros", "rt-multi-thread"]}
config = "0.15.25"
uuid = {version = "1.24.0", features = ["v4"]}
chrono = "0.4.15"
once_cell = "1"
secrecy = { version = "0.8", features=["serde" ]}
unicode-segmentation = "1"
claim = "0.5"
[dependencies.sqlx]
version = "0.8"
default-features = false
features = [
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]
