[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
axum = "0.8.9"
reqwest = "0.13.4"
serde = { version = "1.0.228", features = ["serde_derive"] }
tokio = {version = "1.52.3", features = ["macros", "rt-multi-thread"]}
config = "0.15.25"
uuid = {version = "1.24.0", features = ["v4"]}
chrono = "0.4.15"
[dependencies.sqlx]
version = "0.8"
default-features = false
features = [
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]
