name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'zero2prod/Cargo.toml'
      - 'zero2prod/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        working-directory: zero2prod
        run: cargo deny check advisories
